# Generated by Django 3.1.4 on 2021-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211030_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='Telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
