# Generated by Django 3.1.4 on 2021-10-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetail',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
